config/routes.rb
CIGSL::Application.routes.draw do
  resources :static_pages

  resources :lands do
    resources :photos
    resources :comments
  end

  get "home/index"
  devise_for :users

  root 'home#index'

  

end

app/models/land.rb
class Land < ActiveRecord::Base
  belongs_to :user
  has_many :photos
  has_many :comments
end

app/controllers/lands_controller.rb
class LandsController < ApplicationController
  before_action :set_land, only: [:show, :edit, :update, :destroy]

  # GET /lands
  # GET /lands.json
  def index
    @lands = Land.all
  end

  # GET /lands/1
  # GET /lands/1.json
  def show
  end

  # GET /lands/new
  def new
    @land = Land.new
  end

  # GET /lands/1/edit
  def edit
  end

  # POST /lands
  # POST /lands.json
  def create
    @land = Land.new(land_params)

    respond_to do |format|
      if @land.save
        format.html { redirect_to @land, notice: 'Land was successfully created.' }
        format.json { render action: 'show', status: :created, location: @land }
      else
        format.html { render action: 'new' }
        format.json { render json: @land.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lands/1
  # PATCH/PUT /lands/1.json
  def update
    respond_to do |format|
      if @land.update(land_params)
        format.html { redirect_to @land, notice: 'Land was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @land.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lands/1
  # DELETE /lands/1.json
  def destroy
    @land.destroy
    respond_to do |format|
      format.html { redirect_to lands_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_land
      @land = Land.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def land_params
      params.require(:land).permit(:location, :title_deed, :climatic_condition, :soil_type, :user_id, :map, :size, :description)
    end
end

app/helpers/lands_helper.rb
module LandsHelper
end

app/views/lands/_form.html.erb
<%= form_for(@land) do |f| %>
  <% if @land.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@land.errors.count, "error") %> prohibited this land from being saved:</h2>

      <ul>
      <% @land.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :title_deed %><br>
    <%= f.text_field :title_deed %>
  </div>
  <div class="field">
    <%= f.label :climatic_condition %><br>
    <%= f.text_field :climatic_condition %>
  </div>
  <div class="field">
    <%= f.label :soil_type %><br>
    <%= f.text_field :soil_type %>
  </div>
  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :map %><br>
    <%= f.text_field :map %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lands/edit.html.erb
<h1>Editing land</h1>

<%= render 'form' %>

<%= link_to 'Show', @land %> |
<%= link_to 'Back', lands_path %>

app/views/lands/index.html.erb
<h1>Listing lands</h1>

<table>
  <thead>
    <tr>
      <th>Location</th>
      <th>Title deed</th>
      <th>Climatic condition</th>
      <th>Soil type</th>
      <th>User</th>
      <th>Map</th>
      <th>Size</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @lands.each do |land| %>
      <tr>
        <td><%= land.location %></td>
        <td><%= land.title_deed %></td>
        <td><%= land.climatic_condition %></td>
        <td><%= land.soil_type %></td>
        <td><%= land.user %></td>
        <td><%= land.map %></td>
        <td><%= land.size %></td>
        <td><%= land.description %></td>
        <td><%= link_to 'Show', land %></td>
        <td><%= link_to 'Edit', edit_land_path(land) %></td>
        <td><%= link_to 'Destroy', land, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Land', new_land_path %>

app/views/lands/new.html.erb
<h1>New land</h1>

<%= render 'form' %>

<%= link_to 'Back', lands_path %>

app/views/lands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location:</strong>
  <%= @land.location %>
</p>

<p>
  <strong>Title deed:</strong>
  <%= @land.title_deed %>
</p>

<p>
  <strong>Climatic condition:</strong>
  <%= @land.climatic_condition %>
</p>

<p>
  <strong>Soil type:</strong>
  <%= @land.soil_type %>
</p>

<p>
  <strong>User:</strong>
  <%= @land.user %>
</p>

<p>
  <strong>Map:</strong>
  <%= @land.map %>
</p>

<p>
  <strong>Size:</strong>
  <%= @land.size %>
</p>

<p>
  <strong>Description:</strong>
  <%= @land.description %>
</p>

<%= link_to 'Edit', edit_land_path(@land) %> |
<%= link_to 'Back', lands_path %>